### ISSUE TITLE
Apple Calendar Widget Error

### ISSUE THREAD

**Issue by mvan231** [FWeinb/sb-layout#1]
I am seeing this error: "2021-02-11 04:12:17: Error on line 50:18: ReferenceError: Can't find variable: render"

not quite sure why though. All I did was download the code and run it

**Comment by FWeinb** [comment]
You need to copy the content of [index.js](https://github.com/FWeinb/sb-layout/blob/main/index.js) below the code in that example. This makes updating the library simpler as I don't need to worry about the examples containing an old version of the shared code.

**Comment by mvan231** [comment]
That did the trick. Sorry for delay in getting back to you. Somehow I didn't see your reply
